name: Generate Repo Visualization

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate visualization
        uses: githubocto/repo-visualizer@0.9.1
        with:
          output_file: diagram.svg
          should_push: true
